spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 626c3bf468e6672a644f
            client-secret: e5b7e172c91c61c456f199561c37a25dc6ef803b
server:
  port: 8082